export type CssMainColor =
  | "white"
  | "primary"
  | "secondary"
  | "brightBlue"
  | "lightBlue"
  | "crimsonRed"
  | "lightPink"
   "darkGreen"
  | "plateGreen"
  | "mintGreen"
  | "skyBlue"
  | "warmOrange"
  | "charcoalGray"
  | "lightGray"
  | "mediumBlue"
  | "royalBlue"
  | "iceBlue"
  | "rubyRed"
  | "softPetalPink"
  | "forestGreen"
  | "freshSnow"
  | "orangeMain"
  | "grayF5"
  | "black";
